"""Generate an automated plan-doneness audit snapshot.

This script scans docs/plans/{planned,implemented} for markdown plan files,
extracts status metadata, and writes a dated audit report under docs/plans/.
"""

from __future__ import annotations

import argparse
import logging
import re
from dataclasses import dataclass
from datetime import date
from pathlib import Path

logger = logging.getLogger(__name__)

STATUS_RE = re.compile(r"^Status:\s*(.+?)\s*$", re.MULTILINE)
TITLE_RE = re.compile(r"^#\s+(.+?)\s*$", re.MULTILINE)


@dataclass(frozen=True, slots=True)
class PlanRecord:
    """Canonical metadata extracted from a plan markdown file.

    Attributes:
        path: File path relative to repository root.
        title: Top-level markdown title.
        status: Parsed status line value.
        bucket: Parent bucket inferred from directory placement.
        verdict: Audit verdict derived from status + bucket.
    """

    path: Path
    title: str
    status: str
    bucket: str
    verdict: str


def _extract_title(text: str, fallback: str) -> str:
    """Extract first markdown H1 title.

    Args:
        text: Raw markdown content.
        fallback: Fallback title value if no heading exists.

    Returns:
        Parsed title string.
    """

    match = TITLE_RE.search(text)
    if match:
        return match.group(1).strip()
    return fallback


def _extract_status(text: str) -> str:
    """Extract plan status from markdown.

    Args:
        text: Raw markdown content.

    Returns:
        Parsed status value, or "Unknown" when absent.
    """

    match = STATUS_RE.search(text)
    if match:
        return match.group(1).strip()
    return "Unknown"


def _verdict_for(bucket: str, status: str) -> str:
    """Map bucket/status to a doneness verdict.

    Args:
        bucket: Directory classification (planned or implemented).
        status: Parsed status line.

    Returns:
        Verdict label for audit summary.
    """

    normalized = status.lower()
    if bucket == "implemented":
        if normalized.startswith("implemented"):
            return "Implemented"
        return "Drift (Implemented dir, non-Implemented status)"

    if normalized.startswith("implemented"):
        return "Ready to move to implemented"
    if "partially implemented" in normalized:
        return "Partially implemented"
    if normalized.startswith("planned"):
        return "Planned"
    return "Unknown"


def collect_plan_records(plans_root: Path) -> list[PlanRecord]:
    """Collect plan records from planned and implemented directories.

    Args:
        plans_root: Root path for docs/plans.

    Returns:
        Sorted list of plan records.
    """

    records: list[PlanRecord] = []
    for bucket in ("planned", "implemented"):
        base = plans_root / bucket
        if not base.exists():
            continue

        for path in sorted(base.glob("*.md")):
            text = path.read_text(encoding="utf-8")
            title = _extract_title(text, fallback=path.stem)
            status = _extract_status(text)
            verdict = _verdict_for(bucket, status)
            records.append(
                PlanRecord(
                    path=path,
                    title=title,
                    status=status,
                    bucket=bucket,
                    verdict=verdict,
                )
            )

    records.sort(key=lambda item: str(item.path))
    return records


def render_audit(records: list[PlanRecord], audit_day: date) -> str:
    """Render markdown audit snapshot.

    Args:
        records: Parsed plan metadata entries.
        audit_day: Audit date.

    Returns:
        Markdown document.
    """

    implemented = sum(record.verdict == "Implemented" for record in records)
    partial = sum(record.verdict == "Partially implemented" for record in records)
    planned = sum(record.verdict == "Planned" for record in records)
    drift = sum("Drift" in record.verdict for record in records)
    move_ready = sum(
        record.verdict == "Ready to move to implemented" for record in records
    )
    unknown = sum(record.verdict == "Unknown" for record in records)

    lines = [
        f"# Plan Doneness Auto-Audit ({audit_day.isoformat()})",
        "",
        "Status: Audit Report (Auto-Generated)",
        "",
        "Note: Generated by `scripts/audit_plans_doneness.py`.",
        "",
        "## Summary",
        f"- Total plans scanned: {len(records)}",
        f"- Implemented: {implemented}",
        f"- Partially implemented: {partial}",
        f"- Planned: {planned}",
        f"- Ready to move to implemented: {move_ready}",
        f"- Drift: {drift}",
        f"- Unknown: {unknown}",
        "",
        "## Plan Status Table",
        "| File | Bucket | Status | Verdict |",
        "|---|---|---|---|",
    ]

    for record in records:
        row = (
            f"| `{record.path.as_posix()}` | {record.bucket} | "
            f"{record.status} | {record.verdict} |"
        )
        lines.append(row)

    lines.extend(
        [
            "",
            "## Follow-ups",
            "- Move any 'Ready to move to implemented' plans into "
            "`docs/plans/implemented/`.",
            "- Resolve any drift or unknown-status entries before release.",
        ]
    )
    return "\n".join(lines) + "\n"


def write_audit(plans_root: Path, report_text: str, audit_day: date) -> Path:
    """Write auto-audit report to docs/plans.

    Args:
        plans_root: Root path for docs/plans.
        report_text: Rendered markdown content.
        audit_day: Date stamp for filename.

    Returns:
        Output path.
    """

    output = plans_root / f"plan-doneness-audit-auto-{audit_day.isoformat()}.md"
    output.write_text(report_text, encoding="utf-8")
    return output


def parse_args() -> argparse.Namespace:
    """Parse CLI args."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--plans-root",
        default="docs/plans",
        help="Path to plans root directory (default: docs/plans)",
    )
    parser.add_argument(
        "--date",
        default=None,
        help="Audit date in YYYY-MM-DD format (default: today)",
    )
    return parser.parse_args()


def main() -> int:
    """Run auto-audit generation command.

    Returns:
        Process exit code.
    """

    logging.basicConfig(level=logging.INFO, format="%(message)s")
    args = parse_args()

    plans_root = Path(args.plans_root)
    if not plans_root.exists():
        logger.error("Plans root does not exist: %s", plans_root)
        return 1

    audit_day = date.fromisoformat(args.date) if args.date else date.today()
    records = collect_plan_records(plans_root)
    output = write_audit(plans_root, render_audit(records, audit_day), audit_day)
    logger.info("Wrote plan auto-audit: %s", output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
